haskell-infra/hl

static/markdown/linux-install.md
Since Fedora is a widely used distro there should be install instructions for it.
=> add ghc 7.8.4 install instructions for Fedora 21

README.md, scripts/pull-build
The build instructions fail because there is no submodule called `submodules/senza` anymore.
=> No submodules are required since #15.

static/js/tryhaskell.pages.js
The previous example with `foldr (:) [] [1,2,3]` was a bit obscure for newbies and did not bring much, since the result is the same as argument 3. Replaced with example with `map (+1)  [1,2,3]`, very readable even without knowing haskell and using partial application and higher order function.
=> changed example in "Try it" from foldr to map

static/markdown/linux-install.md
This way $PATH will get inserted as a variable, as currently it will get expanded by the shell and get hardcoded in `~/.bashrc`.
=> Fix automatic PATH expansion in Linux setup guide

static/js/jquery.console.js
jquery creates a hidden textarea, which enables Android's
autocorrection, spellchecker, and so on. Those only affect letters,
which is why only the letters refused to appear. I added html attributes
on the textarea to disable those features, and now the letters can be
typed just fine.
I have also sent an identical pull request upstream to chrisdone/jquery-console.
=> fix #50 by modifying jquery.console.js

static/markdown/windows-install.md
We're not going to update to 7.10 until it happens uniformly for Mac and Linux too. In the meantime this points to the latest in the 7.8 series, removes the now-extraneous instructions to install alex and happy, and also points to the minghc page for other versions.
=> update windows installer pointer

src/HL/View/Home.hs
Apologies, but I'd like to head off more posts like this: https://news.ycombinator.com/item?id=9541478
I *hate* bikeshedding nomenclature but this could prevent some objections.
=> Don't call it a sieve

static/markdown/linux-install.md
Some applications (leksah, ghcjs, which, ...) cannot use a path if ~ is not expanded by bash.
=> Remove quotes so tilde is expanded

src/HL/View/Downloads.hs
This change will work with either the existing Haskell Platform web pages or the new ones which we will install after 7.10.2 is released.
=> Updated Haskell Platform section of the Downloads page.

static/markdown/windows-install.md
* Includes `stack`
* Fix bug when `PATH` gets really long
These links still point to 7.8.4. Are we ready to expose direct links to 7.10.2 yet?
=> Use 2015-08-05 MinGHC installers

static/markdown/windows-install.md
* Point to MinGHC installer builds for 2015-08-13
* Point to installers for GHC 7.10.2 instead of 7.8.4
* Update description of MinGHC since it now includes `stack`
* Remove Haskell Platform links since they are now on the Downloads page
=> Point to MinGHC 2015-08-13 links; use GHC 7.10.2

static/markdown/linux-install.md
This removes unsupported operations on the Arch Linux distribution and cuts down on additional unnecessary information.
=> Remove dangerous recommendations and simplify.

src/HL/View/Community.hs
Add Seattle Area Haskell Users' Group link to Community page
=> Add Seattle Area Haskell Users' Group link

src/HL/View/Documentation.hs
Positioned near the top, as it seems good and more up to date than RWH/LYAH
=> add Haskell Programming book

static/markdown/downloads-main.md
Added "Haskell IDEs & other distributions" paragraph
=> Refer to other distributions on Downloads page

static/markdown/downloads-main.md
- docs.haskellstack.org doesn't have valid TLS cert so visitors will get an error
- readthedocs.com supports custom TLS, but it isn't configured or is broken for docs.haskellstack.org
=> Use plain HTTP for Haskell Stack links

src/HL/View/Template.hs
"Got changes to contribute" is ambiguous with respect to GHC and the homepage. I was looking for the other, so now I have changes to contribute.
=> Clarify contributor call to action

src/HL/View/Home.hs
The grammar wasn't entirely wrong, but it wasn't entirely right, either. So I fixed it!
=> Change subhead copy underneath the Haskell logo

static/markdown/mailing-lists.md
So given the current climate, I thought it might be worth it to add the Haskell-community mailing list to the Mailing List page of the site. Right now it's pretty obscure and if it's to be useful to the wider community, then it should have a more prominent position than it currently has as to communicate that it's actually used for pretty significant decision-making and if you want to be involved in said decisions, you should sign up.
Let me know if there's any improvements I can make.
=> Add Haskell-community to mailing-list.md.

src/HL/View/Documentation.hs
Graham Hutton recently published a new edition of his book "Programming in Haskell".
This commit simply updates the book's official URL.
=> Updates link to Graham Hutton's book

src/HL/View/Template.hs
Update the copyright text for the new year, from "© 2014–2016 haskell.org" to "© 2014–2017 haskell.org".
=> 2016 => 2017

src/HL/View/Community.hs
Still working on taking over the BayHac website. The wiki is a better place to reference BayHac right now.
=> BayHac link to wiki

static/markdown/linux-install.md
- first command on line has the `sudo`
- Without it for the second line, will fail with permission error
=> fix missing sudo prefix in Debian install command

src/HL/View/Community.hs
Please merge `Community.hs` to add link of haskell-jp.
Thank you.
=> Add haskell-jp (Japan Haskell Users Group)

src/HL/View/Documentation.hs
The link now points directly to a PDF of the latest revision of the book. I'm not sure if that's the best idea, but I wasn't able to find an official page that points to it.
=> Fix "The Haskell School of Music" broken link

src/HL/View/Template.hs
This is similar to a change made last year (https://github.com/haskell-infra/hl/pull/190/commits/3fe25c0774b1882fa5fd09e7204316d544531ca5).
This changes the copyright text from "© 2014–2017 haskell.org" to "© 2014–2018 haskell.org".
=> Updated copyright 2017 => 2018

src/HL/View/Community.hs
We have a spiffy new web site at http://seattlehaskell.org/. I would like the Community page to link to this.
=> Update Seattle Area Haskell Users' Group link

src/HL/View/Documentation.hs
This commit is based on #227, but with an erroneous `]` removed.
=> Add 'Get Programming with Haskell' to book list

src/HL/Model/Videos.hs
Here's a suggestion for 6 new videos on the landing page, based on the discussion in #228. I tried to pick ones that are enthusiastic, that show how Haskell solves various problems, and that are relatable for people in industry as well as students. I'd be happy to get feedback and suggestions if you think there are better ones.
Also @gbaz, do you think we should get permission from the speakers in these videos? I'm not sure about that aspect.
Thanks!
=> Add new videos on home page
